name: spring-petclinic

trigger:
- main

pool:
  name: Devops

stages:
- stage: Build 
  jobs:
  - job: sonarqube
    displayName: sonarqube-analysis
    timeoutInMinutes: 10 # Adjust this if your build takes longer
    steps:
     - task: SonarQubePrepare@6
       inputs:
          SonarQube: 'Sonarqube'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'Petclinic'
          cliProjectName: 'Petclinic'
          cliSources: '.'
          extraProperties: |
            # Additional properties that will be passed to the scanner, 
            # Put one key=value per line, example:
            # sonar.exclusions=**/*.bin
            sonar.java.binaries=.
        
     - task: SonarQubePublish@6
       inputs:
         pollingTimeoutSec: '300'

     - task: SonarQubeAnalyze@6
       inputs:
         jdkversion: 'JAVA_HOME_17_X64'