name: spring-petclinic

trigger:
- main

pool:
  name: Devops

stages:
- stage: Build 
  jobs:
  - job: Maven
    timeoutInMinutes: 10 # Adjust this if your build takes longer
    steps:
      - task: SonarQubePrepare@6
        inputs:
         SonarQube: # string. Required. SonarQube Server Endpoint. 
         scannerMode: 'other'
         projectKey: 'Petclinic'
         projectName: 'Petclinic'
         projectVersion: '$(Build.BuildId)'

      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
