name: spring-petclinic-$(build.buildId)

trigger:
- main

pool:
  name: Devops

stages:

- stage: Build
  jobs:
  - job: BuildAndAnalyze
    displayName: 'Build and Analyze'
    steps:
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'Sonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'Petclinic'
        cliProjectName: 'Petclinic'
        cliSources: '.'
        extraProperties: |
          sonar.java.binaries=.

    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

  - job: AzureStorage
    displayName: 'push artifact to Azure Storage'
    steps:
    - task: AzureFileCopy@6
      inputs:
        SourcePath: '$(Build.SourcesDirectory)/target'
        azureSubscription: 'Azure'
        Destination: 'AzureBlob'
        storage: 'azurestorage887766'
        ContainerName: 'artifacts'
        BlobPrefix: '$(Build.BuildId)'
        AdditionalArgumentsForBlobCopy: '--parameter */.jar'

      