name: spring-petclinic-$(build.buildId)

trigger:
- main

pool:
  name: Devops

stages:
- stage: Build 
  jobs:
  - job: Sonarqube
    displayName: sonarqube-analysis
    steps:
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'Sonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'Petclinic'
        cliProjectName: 'Petclinic'
        cliSources: '.'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.java.binaries=.
    

    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'

    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'