name: spring-petclinic

trigger:
- main

pool:
  name: Devops

stages:
- stage: Build 
  jobs:
  - job: Sonarqube
    displayName: sonarqube-analysis
    timeoutInMinutes: 10 # Adjust this if your build takes longer
    steps:
     - task: SonarQubePrepare@6
       inputs:
          SonarQube: 'Sonarqube'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'Petclinic'
          cliProjectName: 'Petclinic'
          cliSources: '.'
          extraProperties: |
            # Additional properties that will be passed to the scanner, 
            # Put one key=value per line, example:
            # sonar.exclusions=**/*.bin
            sonar.java.binaries=.
        
     - task: SonarQubePublish@6
       inputs:
         pollingTimeoutSec: '300'

     - task: SonarQubeAnalyze@6
       inputs:
         jdkversion: 'JAVA_HOME_17_X64'

  - job: Maven
    dependsOn: Sonarqube
    displayName: Java Artifact with Maven
    timeoutInMinutes: 10 # Adjust this if your build takes longer
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

  - job: CopyArtifacts
    pool: Devops
    dependsOn: Maven
    displayName: CopyArtifacts
    steps:
    - checkout: none
    - task: AzureFileCopy@6
      inputs:
        SourcePath: '*'
        azureSubscription: 'Azure'
        Destination: 'AzureBlob'
        storage: 'devopsstorage887766'
        ContainerName: 'devops'