name: spring-petclinic-$(build.buildId)

trigger:
- main

pool:
  name: Devops

stages:

- stage: Build
  jobs:
  - job: BuildAndAnalyze
    displayName: 'Build and Analyze'
    steps:
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'Sonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'Petclinic'
        cliProjectName: 'Petclinic'
        cliSources: '.'
        extraProperties: |
          sonar.java.binaries=.

    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false    

#- stage: Artifacts
#  jobs:
#  - job: UploadArtifacts
#    displayName: 'Upload Build Artifacts To Azure Storage'
#    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az storage blob upload-batch --account-name $(STORAGE) --account-key $(STORAGE_KEY) --destination devops/$(Build.BuildId) --source $(Build.SourcesDirectory)/target --pattern *.jar

- stage: Docker
  jobs:
  - job: BuildAndPushImage
    displayName: 'Build and Push Docker Image'
    steps:
    - task: Docker@2
      displayName: 'Build and push docker image to docker hub and ACR'
      inputs:
        containerRegistry: 'Docker'
        repository: 'udaykumarreddy995/javaapp77'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
    - script: docker images
      displayName: 'List the docker images'