name: spring-petclinic

trigger:
- main

pool:
  name: Devops

stages:
- stage: Build 
  jobs:
  - job: Maven
    steps:
    
    - script: bash |
       mvn clean verify sonar:sonar \
        -Dsonar.projectKey=Petclinic1 \
        -Dsonar.host.url=http://13.82.41.1:9000 \
        -Dsonar.login=sqa_c6317d75e5f091059ef9ef0d4a4f2b91d43600e8
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false