name: spring-petclinic-$(build.buildId)

trigger:
- main

pool:
  name: Devops

stages:

- stage: Build
  jobs:
  - job: BuildAndAnalyze
    displayName: 'Build and Analyze'
    steps:
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'Sonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'Petclinic'
        cliProjectName: 'Petclinic'
        cliSources: '.'
        extraProperties: |
          sonar.java.binaries=.

    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'