name: spring-petclinic

trigger:
- main

pool:
  name: Devops

stages:
- stage: Build 
  jobs:
  - job: Maven
    steps:
    
    - script: bash |
       mvn sonar:sonar
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false