name: spring-petclinic

trigger:
- main

pool:
  name: $(agent1)

stages:
- stage: Build 
  jobs:
  - job: Maven
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false       

  - job: SonarQube
    dependsOn: Maven
    steps:
    - script: bash |
        mvn clean package -Dcheckstyle.skip=true sonar:sonar \
        -Dsonar.login=$(SONAR_TOKEN)
