# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: spring-petclinic

trigger:
- main

pool:
  name: $(agent1)

stages:
- stage: Build 
  jobs:
  - job: Maven
    steps:
    - task: Maven@4
      inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false       

  - job: SonarQube
    steps:
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'SonarQube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sqa_4b65ec74b10201a234470bf64b2915a2fdeeff74'
        cliProjectName: 'spring-petclinic'
        cliSources: '.'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          #sonar.java.binaries=.
    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'
    
    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'