name: spring-petclinic-$(build.buildId)

trigger:
- main

pool:
  name: Devops

stages:

- stage: Build
  jobs:
  - job: BuildAndAnalyze
    displayName: 'Build and Analyze'
    steps:
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'Sonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'Petclinic'
        cliProjectName: 'Petclinic'
        cliSources: '.'
        extraProperties: |
          sonar.java.binaries=.

    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

  - job: AzureStorage
    dependsOn: BuildAndAnalyze
    displayName: 'push artifact to Azure Storage'
    steps:
    - checkout: none
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az storage blob upload-batch --account-name $(STORAGE) --account-key $(STORAGE_KEY) --destination artifacts/$(Build.BuildId) --source $(Build.SourcesDirectory)/target --pattern *.jar'