name: spring-petclinic-$(build.buildId)

trigger:
- main

pool:
  name: Devops
  demands: []

stages:
- stage: Build 
  jobs:
  - job: Sonarqube
    displayName: sonarqube-analysis
    timeoutInMinutes: 10 # Adjust this if your build takes longer
    steps:
     - task: SonarQubePrepare@6
       inputs:
          SonarQube: 'Sonarqube'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'Petclinic'
          cliProjectName: 'Petclinic'
          cliSources: '.'
          extraProperties: |
            # Additional properties that will be passed to the scanner, 
            # Put one key=value per line, example:
            # sonar.exclusions=**/*.bin
            sonar.java.binaries=.
        
     - task: SonarQubePublish@6
       inputs:
         pollingTimeoutSec: '300'

     - task: SonarQubeAnalyze@6
       inputs:
         jdkversion: 'JAVA_HOME_17_X64'

  - job: Maven
    dependsOn: Sonarqube
    displayName: Java Artifact with Maven
    timeoutInMinutes: 10 # Adjust this if your build takes longer
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

  - job: CopyArtifacts
    dependsOn: Maven
    displayName: CopyArtifacts
    steps:
    - checkout: none
    
    - task: CopyFiles@2
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)'    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az storage blob upload-batch --account-name devopsstorage887766 --account-key $(STORAGE_KEY) --destination devops --source $(Build.ArtifactStagingDirectory)
    