name: spring-petclinic

trigger:
- main

pool:
  name: $(agent1)

stages:
- stage: Build 
  jobs:
  - job: Maven
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false       

  - job: SonarQube
    dependsOn: Maven
    steps:
    - script: bash |
       mvn clean package -Dcheckstyle.skip=true sonar:sonar -Dsonar.login=$(SONAR_TOKEN) \
       -Dsonar.exclusions=**/*.bin \
       -Dsonar.java.binaries=.

    
    #- task: SonarQubePrepare@6
    #  inputs:
    #    SonarQube: 'SonarQube'
    #    scannerMode: 'CLI'
    #    configMode: 'manual'
    #    cliProjectKey: 'sqa_4b65ec74b10201a234470bf64b2915a2fdeeff74'
    #    cliProjectName: 'spring-petclinic'
    #    cliSources: '.'
    #    extraProperties: |
    #      # Additional properties that will be passed to the scanner, 
    #      # Put one key=value per line, example:
    #      # sonar.exclusions=**/*.bin
    #      sonar.java.binaries=.
    #      # Uncomment if using Developer Edition or higher for branch analysis
    #      # sonar.branch.name=$(Build.SourceBranchName)
#
    #- task: SonarQubePublish@6
    #  inputs:
    #    pollingTimeoutSec: '300'
#
    #- task: SonarQubeAnalyze@6
