name: spring-petclinic-$(build.buildId)

trigger:
- main

pool:
  name: Devops

stages:
- stage: Build 
  jobs:
  - job: Sonarqube
    displayName: sonarqube-analysis
    steps:
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'Sonarqube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'Petclinic'
        cliProjectName: 'Petclinic'
        cliSources: '.'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.java.binaries=.
    

    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'

    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

  - job: Maven
    dependsOn: Sonarqube
    displayName: 'Build the Artifact'
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: AzureCLI@2
      inputs:
          azureSubscription: 'Azure'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az storage blob upload-batch --account-name $(STORAGE) --account-key $(STORAGE_KEY) --destination devops/$(Build.BuildId) --source $(Build.SourcesDirectory)/target --pattern *.jar
      